### ISSUE TITLE
Missing schemes for velthuis and kolkata

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#12]
They are noted at https://github.com/sanskrit-coders/indic_transliteration/blob/master/indic_transliteration/sanscript.py#L106 and https://github.com/sanskrit-coders/indic_transliteration/blob/master/indic_transliteration/sanscript.py#L100, but absent in scheme definition. Raises an error.
```python
>>> from indic_transliteration import sanscript
>>> sanscript.transliterate('Davala', 'slp1', 'velthuis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\indic_transliteration\sanscript.py", line 349, in transliterate
    scheme_map = _get_scheme_map(_from, _to)
  File "C:\Python27\lib\site-packages\backports\functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\indic_transliteration\sanscript.py", line 325, in _get_scheme_map
    return SchemeMap(SCHEMES[input_encoding], SCHEMES[output_encoding])
KeyError: 'velthuis'
```

**Comment by drdhaval2785** [comment]
Yes. It would be needed for me and others.

**Comment by vvasuki** [comment]
Added Kolkata at 1.6.3 .

I like it's ē and ō better than IAST.

**Comment by vvasuki** [comment]
Added Velthuis in next version as well.
