### ISSUE TITLE
Transliterating to Telugu fails with KeyError

### ISSUE THREAD

**Issue by ChillarAnand** [sanskrit-coders/indic_transliteration#13]
```sh
echo 'raamayanam' > telugu.txt 
python indic_transliteration/little/transliterator.py telugu.txt "CYRILLIC" "TELUGU"
```
It fails with 
```py 
b'\xe0\xa4\x9c\xe0\xa4\xaf \xe0\xa4\x97\xe0\xa4\xa3\xe0\xa5\x86\xe0\xa4\xb6! \xe0\xa4\xb6\xe0\xa5\x8d\xe0\xa4\xb0\xe0\xa5\x80\xe0\xa4\xb0\xe0\xa4\xbe\xe0\xa4\xae\xe0\xa4\x9c\xe0\xa4\xaf\xe0\xa4\xae\xe0\xa5\x8d'
Traceback (most recent call last):
  File "indic_transliteration/little/transliterator.py", line 419, in findFormat
    fmt = _names[fmt.upper()]
KeyError: 'TELUGU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "indic_transliteration/little/transliterator.py", line 1025, in <module>
    sys.exit(main())
  File "indic_transliteration/little/transliterator.py", line 1019, in main
    print (transliterate(text, inFormat, outFormat).strip('\n'))
  File "indic_transliteration/little/transliterator.py", line 424, in transliterate
    outFormat = findFormat(outFormat)
  File "indic_transliteration/little/transliterator.py", line 421, in findFormat
    raise (ValueError, 'unrecognised format ' + fmt)
TypeError: exceptions must derive from BaseException
```

**Comment by vvasuki** [comment]
No one here has really  worked on that script - if you can contribute a patch, that would be great!

**Comment by ChillarAnand** [comment]
Sure. 

Which languages does it support in current version? It is throwing same error message for hindi, sanksrit.

```py
python indic_transliteration/little/transliterator.py telugu.txt "CYRILLIC" "SANSKRIT"
b'\xe0\xa4\x9c\xe0\xa4\xaf \xe0\xa4\x97\xe0\xa4\xa3\xe0\xa5\x86\xe0\xa4\xb6! \xe0\xa4\xb6\xe0\xa5\x8d\xe0\xa4\xb0\xe0\xa5\x80\xe0\xa4\xb0\xe0\xa4\xbe\xe0\xa4\xae\xe0\xa4\x9c\xe0\xa4\xaf\xe0\xa4\xae\xe0\xa5\x8d'
Traceback (most recent call last):
  File "indic_transliteration/little/transliterator.py", line 419, in findFormat
    fmt = _names[fmt.upper()]
KeyError: 'SANSKRIT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "indic_transliteration/little/transliterator.py", line 1025, in <module>
    sys.exit(main())
  File "indic_transliteration/little/transliterator.py", line 1019, in main
    print (transliterate(text, inFormat, outFormat).strip('\n'))
  File "indic_transliteration/little/transliterator.py", line 424, in transliterate
    outFormat = findFormat(outFormat)
  File "indic_transliteration/little/transliterator.py", line 421, in findFormat
    raise (ValueError, 'unrecognised format ' + fmt)
TypeError: exceptions must derive from BaseException
```

**Comment by vvasuki** [comment]
Try replacing Sanskrit in your command with devanagari.

The following seem to be supported.
```
DEVANAGARI
    IAST
    ITRANS
    HarvardKyoto
    
CYRILLIC
```

You may be interested in using sancript (in the parent package) instead.

**Comment by ChillarAnand** [comment]
Thanks @vvasuki
