### ISSUE TITLE
Problem with Python2

### ISSUE THREAD

**Issue by lokeshh** [sanskrit-coders/indic_transliteration#23]
```
>>> from indic_transliteration import sanscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lokesh/.local/lib/python2.7/site-packages/indic_transliteration/sanscript.py", line 66, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

**Comment by codito** [comment]
@lokeshh how did you install `indic_transliteration`? Did you do it with `pip`? May be the dependencies weren't installed for some reason.

It worked for me in a temporary virtualenv.

```sh
> cd /tmp
> virtualenv2 py2
New python executable in /tmp/py2/bin/python2
Also creating executable in /tmp/py2/bin/python
Installing setuptools, pip, wheel...done.

> cd /tmp/py2 
> ls
> source bin/activate
> pip install indic_transliteration
> python
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from indic_transliteration import sanscript
>>> 
> pip freeze
backports.functools-lru-cache==1.5
indic-transliteration==1.7.4
regex==2018.11.7
```

**Comment by lokeshh** [comment]
Yes I installed using `pip`.

```
> pip2 install indic_transliteration
Collecting indic_transliteration
  Using cached https://files.pythonhosted.org/packages/c1/8e/658fa4ba43dbef7d3899c1372e160092c9b77e03ad2e2088b9881ba51512/indic_transliteration-1.7.4-py2.py3-none-any.whl
Collecting regex (from indic_transliteration)
Collecting backports.functools-lru-cache (from indic_transliteration)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: regex, backports.functools-lru-cache, indic-transliteration
Successfully installed backports.functools-lru-cache-1.5 indic-transliteration-1.7.4 regex-2018.11.7
```

**Comment by codito** [comment]
ok, it should work since `backports.functools-lru-cache` is installed. Could it be that the site-packages directory is incorrectly looked up?

What does `ls /home/lokesh/.local/lib/python2.7/site-packages` show?

**Comment by lokeshh** [comment]
```
> ls /home/lokesh/.local/lib/python2.7/site-packages 
argparse-1.4.0.dist-info  backports.functools_lru_cache-1.2.1.dist-info        indic_transliteration-1.7.4.dist-info  regex-2018.11.7.dist-info  regex.pyc
argparse.py               backports.functools_lru_cache-1.2.1-py3.5-nspkg.pth  indic_transliteration_unmaintained     _regex_core.py             _regex.so
argparse.pyc              backports.functools_lru_cache-1.5.dist-info          powerline_shell                        _regex_core.pyc            test_regex.py
backports                 indic_transliteration                                powerline_shell-0.7.0.dist-info        regex.py                   test_regex.pyc
> ls /home/lokesh/.local/lib/python2.7/site-packages/backports
functools_lru_cache.py  functools_lru_cache.pyc  __init__.py  __init__.pyc

**Comment by vvasuki** [comment]
We actually dropped python2 support with https://github.com/sanskrit-coders/indic_transliteration/commit/caab573f0b5a19ba520840762974025808c3d330

**Comment by lokeshh** [comment]
@vvasuki I see. I think I can still use an old version.
