### ISSUE TITLE
Devanagari to English

### ISSUE THREAD

**Issue by khowal** [sanskrit-coders/indic_transliteration#24]
Hi !

I am trying to transliterate Hindi to English, I got the following error, when tried.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/indic_transliteration/sanscript.py", line 385, in transliterate
    return func(data, scheme_map, **options)
  File "/Library/Python/2.7/site-packages/indic_transliteration/sanscript.py", line 307, in _roman
    return ''.join(buf)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)

**Comment by vvasuki** [comment]
try python 3
