### ISSUE TITLE
TypeError: descriptor 'split' requires a 'unicode' object but received a 'str'

### ISSUE THREAD

**Issue by pmshukla** [sanskrit-coders/indic_transliteration#36]
>>> from indic_transliteration import xsanscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pranav/.local/lib/python2.7/site-packages/indic_transliteration/xsanscript.py", line 122, in <module>
    _setup()
  File "/home/pranav/.local/lib/python2.7/site-packages/indic_transliteration/xsanscript.py", line 74, in _setup
    'vowels': sanscript.SCHEMES[DEVANAGARI]['vowels'] + s("""ऎ ऒ"""),
TypeError: descriptor 'split' requires a 'unicode' object but received a 'str'
>>> 
I am getting this error when importing xsanscript. Kindly help me with the issue

**Comment by pmshukla** [comment]
had got an error with python2.X and python 3.X
